**Teoría NumPy**

¿Qué significa NumPy?-->Numerical Python
Ofrece una librería de matrices multidimensionales. (ndarray)

Requisitos
1. Instalar Visual Studio Code
2. Instalar Python version 3.9 o 3.10
3. Seleccionar el intérprete de Python en el VSC, pulsado Ctl+Shift+P
4. Instalar extensión Jupyter de Microsoft
Una vez realizados los pasos anteriores ya tenéis Jupyter Notebook instalados (también tenéis un enlace en Classroom
con las instucciones en la página web oficial de Visual Studio Code.)

Pasos para crear un archivo Jupyter Notebook
1. Iniciando Visual Studio Code, abrir carpeta donde váis a guardar los archivos JupyterNotebook para la UT2.
2. Abrir archivo (Ctl+N) seleccionar Python y guardarlo como archivo .ipynb
3. Listo para trabajar con Jupyter Notebooks.

Seguir con la instalación de la librería NumPy, con el siguiente comando
pip install numpy

**Comentario**: El código que váis a ejecutar tiene que estar en la celda code. El texto se puede escribir en la celda Markdown.

La **ventaja** de los Jupyter Notebook es que podemos ejecutar código Python a trozos (en una celda Code)!

A] CREAR UNA MATRIZ CON NUMPY

In [1]:
# Comentarios en la celda code.
# pip install numpy

import numpy as np

matriz= np.array([1,2,3,4])
print(matriz)
matriz[-1]

[1 2 3 4]


4

In [2]:
#Una matriz puede contener sólo un tipo de datos. Vamos a ver qué tipo de datos hay en la matriz anterior.
matriz.dtype

dtype('int64')

In [3]:
#¿Qué pasa con una matriz con diferentes tipos de datos?
matrizMix=np.array([1,2.4,5,3.14])
matrizMix.dtype

dtype('float64')

In [4]:
matrizMix2=np.array([2,4,6,"letra"])
matrizMix2.dtype

dtype('<U21')

B] Matriz Multidimensional

In [5]:
# 1D
matriz1D=np.array([12,23,34,45,56,67,78])
print(matriz1D)

# 2D
matriz2D=np.array([
    [1,2,3],[4,5,6],[7,8,9]
])
print(matriz2D)

#3D
matriz3D=np.array([[[1,2,3]],[[3,4,5]],[[6,7,8]]])
print(matriz3D)

[12 23 34 45 56 67 78]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1 2 3]]

 [[3 4 5]]

 [[6 7 8]]]


In [6]:
# Lo mismo con ceros y unos
matriz1D=np.zeros(7)
print(matriz1D)

matriz2D=np.zeros((3,3))
print(matriz2D)

matriz3D=np.ones(((3,1,3)))
print(matriz3D)

[0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[[1. 1. 1.]]

 [[1. 1. 1.]]

 [[1. 1. 1.]]]


In [7]:
# Una matriz con números aleatorios en el intervalo [0,1)
MZaleatoria=np.random.rand(2,2,2,4)
MZaleatoria

array([[[[0.20549518, 0.82734854, 0.21257321, 0.82695355],
         [0.60564189, 0.22845818, 0.30440793, 0.48201584]],

        [[0.93335335, 0.31780081, 0.82243134, 0.30535556],
         [0.82556327, 0.28576205, 0.60976521, 0.72583141]]],


       [[[0.12054146, 0.36682511, 0.80536033, 0.31206793],
         [0.14159235, 0.78973504, 0.72154498, 0.58208326]],

        [[0.98757034, 0.14093858, 0.54476624, 0.99614668],
         [0.64425036, 0.98616612, 0.50667529, 0.01976508]]]])

In [8]:
# Número comun a todos los elementos de la matriz con el método np.full((n_dim,m_dimensiones),número)
MatrizNumerosIguales=np.full((2,1),10)
MatrizNumerosIguales

array([[10],
       [10]])

In [9]:
#Matriz Idéntica
Identica=np.eye(3)
Identica

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Especificando el tipo de las variables dentro de la matriz

In [10]:
matrizEs= np.array((2,3), dtype=np.float32)
matrizEs


array([2., 3.], dtype=float32)

C] Matriz con el np.arange()
    - arange(numero) genera valores en el intervalo **[0,numero)**
    - arange(start,stop) genera valores en el intervalo **[start,stop)**
    - arange(start,stop,step) genera valores en el intervalo **[start,stop)** con espacio el paso **step**

In [11]:
#Intenar C]

D] Dimensiones de una matriz, Shape, Size

In [12]:
M34=np.array([[1,2,3,4],[10,20,32,43],[1,2,3,4]])
print(M34.ndim)
M14=np.array([1,0,1,0])
M14.ndim

2


1

In [13]:
M34.shape[1] # [0]= número filas , [1]= número columnas

4

In [14]:
M34.size # imprime la cantidad de elementos que tiene la matriz (n x m), 3x4-->12

12

E] Reformar una matriz

In [15]:
m1D=np.array([10,20,32,41])
m1D.shape

m2D=m1D.reshape(2,2)
m2D

array([[10, 20],
       [32, 41]])

In [16]:
MUnknown=np.array([[1,2,3,4],[5,6,7,8]])
print(MUnknown.shape)
#print(MUnknown.flatten())
MUnknown.reshape(2,4)

(2, 4)


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

F] Troceando una Matriz

In [17]:
M16=np.array([1,2,3,4]) #Expresión [start:end:step-size] 1D, para 2D [start:end:step-size,start:end:step-size]

#M16[:6:2]
#M16[4:6]
#M16[1::3]

In [18]:
M23=np.array([[1,2,3],[2,4,6]])
#Imprime el número 1, después el 4, después el 6
#print(M23[1,2])

G] Listas vs Matrices NumPy

A continuación se compara la suma de los numeros en el intervalo 1-999 entre funciones de Python y de la librería Numpy.

In [19]:
%%timeit
suma=sum(range(1000))
#print(suma)

26.5 µs ± 11.9 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [20]:
%%timeit
np.sum(np.arange(1000))

6.96 µs ± 1.9 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


I] Matemáticas de Matrices

In [21]:
# genero unas matrices con valores aleatorios del [0, 10) y de [0,5)
M1= np.random.randint(20, size=(3,4))
M2= np.random.randint(1,5, size=(3,4))
print("Matriz 1:")
print(M1)
print("-----------------------------------------------------------")
print("Matriz 1:")
print(M1.T)
# print(M1.transpose())
print("-----------------------------------------------------------")
print("Matriz 2:")
print(M2)
print("-----------------------------------------------------------")

# muestro el valor mínimo, máximo y la suma de los valores de una matriz
print("M1 min: ", M1.min())
print("M1 max: ", M1.max())
print("M1 suma:  ", M1.sum())
print("-----------------------------------------------------------")



Matriz 1:
[[ 1  0  0 13]
 [11 10  3 11]
 [12 19 12  1]]
-----------------------------------------------------------
Matriz 1:
[[ 1 11 12]
 [ 0 10 19]
 [ 0  3 12]
 [13 11  1]]
-----------------------------------------------------------
Matriz 2:
[[3 4 2 2]
 [2 2 3 3]
 [2 4 1 1]]
-----------------------------------------------------------
M1 min:  0
M1 max:  19
M1 suma:   93
-----------------------------------------------------------


In [22]:
# También podemos calcular la raíz cuadrada
print("M1 sqrt: ", np.sqrt(M1))
print("-----------------------------------------------------------")

# Por último, podremos hacer cálculos matemáticos básicos entre matrices. Estos cálculos serán posición a posición
print(M1 + M2)
print(M1 - M2)
print(M1 * M2)
print("La división es: \n ", M1 / M2)
print("-----------------------------------------------------------")
# Multiplicación Matricial. Si intentamos hacer la multiplicación matricial M1 x M2 no se puede, porqué?
print(M1@M2.T)

M1 sqrt:  [[1.         0.         0.         3.60555128]
 [3.31662479 3.16227766 1.73205081 3.31662479]
 [3.46410162 4.35889894 3.46410162 1.        ]]
-----------------------------------------------------------
[[ 4  4  2 15]
 [13 12  6 14]
 [14 23 13  2]]
[[-2 -4 -2 11]
 [ 9  8  0  8]
 [10 15 11  0]]
[[ 3  0  0 26]
 [22 20  9 33]
 [24 76 12  1]]
La división es: 
  [[ 0.33333333  0.          0.          6.5       ]
 [ 5.5         5.          1.          3.66666667]
 [ 6.          4.75       12.          1.        ]]
-----------------------------------------------------------
[[ 29  41  15]
 [101  84  76]
 [138 101 113]]
