# Ejercicios Numpy

---
### Ejercicio 1

Antes de empezar tenéis que importar la libreria adecuada para trabajar con Numpy.

In [257]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 23.3
[notice] To update, run: C:\Users\alumnoTARDE\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [258]:
import numpy as np

---
### Ejercicio 2


Crea un array de **una dimensión** con los 10 valores que tu quieras y muéstralo por pantalla:

In [259]:
array1D=np.array([1,2,3,4,5,6,7,8,9,10])
print(array1D)

[ 1  2  3  4  5  6  7  8  9 10]


---
### Ejercicio 3


Crea un array de distinto nombre al anterior de **dos dimensiones** con los 3x3 valores que tu quieras y muéstrala por pantalla:

In [260]:
array2D=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

print(array2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


---
### Ejercicio 4


Crea un array de distinto nombre a los anteriores de **tres dimensiones** con los 3x2x2 valores que tu quieras y muéstrala por pantalla:

In [261]:
array3D = np.array([[[1, 2],
                         [3, 4]],

                        [[5, 6],
                         [7, 8]],

                        [[9, 10],
                         [11, 12]]])

print(array3D)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


---
### Ejercicio 5

Muestra las **dimensiones, el tamaño y la forma** que tienen las tres matrices creadas anteriormente:

In [262]:
array1D=np.array([1,2,3,4,5,6,7,8,9,10])

array2D=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

array3D = np.array([[   [1, 2],
                         [3, 4]],

                        [[5, 6],
                         [7, 8]],

                        [[9, 10],
                         [11, 12]]])

print("Matriz 1D:")
print("Dimensiones:", array1D.ndim)
print("Tamaño:", array1D.size)
print("Forma:", array1D.shape)

print("\nMatriz 2D")
print("Dimensiones:", array2D.ndim)
print("Tamaño:", array2D.size)
print("Forma:", array2D.shape)

print("\nMatriz 3D:")
print("Dimensiones:", array3D.ndim)
print("Tamaño:", array3D.size)
print("Forma:", array3D.shape)

Matriz 1D:
Dimensiones: 1
Tamaño: 10
Forma: (10,)

Matriz 2D
Dimensiones: 2
Tamaño: 9
Forma: (3, 3)

Matriz 3D:
Dimensiones: 3
Tamaño: 12
Forma: (3, 2, 2)


---
### Ejercicio 6


Crea un array de una dimensión de tipo int8. En una de las posiciones pon el valor 1000. ¿Qué ocurre y porqué?

In [263]:
array1DInt8 = np.array([0, 0, 0], dtype=np.int8)

array1DInt8[1] = 1000

print(array1DInt8)

[  0 -24   0]


C:\Users\alumnoTARDE\AppData\Local\Temp\ipykernel_7128\1048028275.py:3: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 1000 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  array1DInt8[1] = 1000


Da error porque en Python int8 ocupan 8bits (-127 a 127) y 1000 está fuera del rango. 

---
### Ejercicio 7


Crea un array de dos dimensiones de tipo float128 y luego muestra su tipo por pantalla:

In [264]:
# array2DFloat128 = np.array([[1.1, 2.2], [3.3, 4.4]], dtype=np.float128)

# print("Tipo del array2DFloat128:", array2DFloat128.dtype)

---
### Ejercicio 9

Crea un array con los 10 primeros multiplos de 2 en una sola instrucción y muestralo por pantalla

In [265]:
multiplosDe2 = np.arange(2, 21, 2)

print(multiplosDe2)

[ 2  4  6  8 10 12 14 16 18 20]


---
### Ejercicio 10

Crea la siguiente matriz 4x4 con nombre A44=
\begin{pmatrix}
2 & 5 & 0 & 10\\
7 & 3 & 8 & -9\\
3 & 0 & 1 & -1\\
12 & -1 & 0 & 41
\end{pmatrix}


In [266]:
A44 = np.array([
        [2, 5, 0, 10],
        [7, 3, 8, -9],
        [3, 0, 1, -1],
        [12, -1, 0, 41]
    ])

print(A44)

[[ 2  5  0 10]
 [ 7  3  8 -9]
 [ 3  0  1 -1]
 [12 -1  0 41]]


---
### Ejercicio 11

Usa la matriz A44 y muestra por pantalla una submatriz 2x2, por ejemplo
\begin{pmatrix}
3 & 8 \\
0 & 1 \\
\end{pmatrix}

In [267]:
A44 = np.array([
        [2, 5, 0, 10],
        [7, 3, 8, -9],
        [3, 0, 1, -1],
        [12, -1, 0, 41]
    ])

subMatriz = A44[1:3, 1:3]

print(subMatriz)


[[3 8]
 [0 1]]


---
### Ejercicio 12

Genera un array 3x2 con valores aleatorios,muestrala y también imprime la matriz 2x3.

In [268]:
matriz32 = np.random.random((3, 2))

print("Matriz 3x2:")
print(matriz32)

matriz23 = matriz32.T

print("\nMatriz 2x3:")
print(matriz23)


Matriz 3x2:
[[0.25742069 0.12203413]
 [0.71663389 0.07505634]
 [0.25536288 0.09954075]]

Matriz 2x3:
[[0.25742069 0.71663389 0.25536288]
 [0.12203413 0.07505634 0.09954075]]


---
### Ejercicio 13

Compara los tiempos de ejecución entre una lista aleatoria de 1.000.000 de datos con una matriz aleatorio del mismo tamaño con Numpy.

In [269]:
import random
import time

# Tiempo para la Lista
strartLista = time.time()
lista = [random.randint(1, 1000) for i in range(1000000)]
endLista  = time.time()
totalLista  = endLista - strartLista
print("Tiempo de ejecución para la lista aleatoria: " + str(totalLista))

# Tiempo para la Matriz
strartMatriz = time.time()
matriz = np.random.randint(1, 1000, size=(1000000,))
endMatriz = time.time()
totalMatriz = endMatriz - strartMatriz
print("Tiempo de ejecución para la matriz aleatoria: " + str(totalMatriz))

Tiempo de ejecución para la lista aleatoria: 0.4856681823730469
Tiempo de ejecución para la lista aleatoria: 0.0030202865600585938


---
### Ejercicio 14

Genera dos matrices con dimensiones 10x5 y muestra la suma, resta y multiplicación matricial.

In [270]:
matriz1 = np.random.randint(1, 11, size=(10, 5))  # Números aleatorios entre 1 y 10
matriz2 = np.random.randint(1, 11, size=(10, 5))  # Números aleatorios entre 1 y 10

print("Matriz 1:")
print(matriz1)
print("Matriz 2:")
print(matriz2)

suma = matriz1 + matriz2
print("Suma Matricial:")
print(suma)

resta = matriz1 - matriz2
print("Resta Matricial:")
print(resta)

multi = matriz1, matriz2
print("Multiplicación Matricial:")
print(multi)


Matriz 1:
[[ 1  2  4  9  5]
 [ 4 10  2  3 10]
 [ 6  5  5  1  2]
 [ 2  1  2  4  1]
 [ 6  5  5  7  5]
 [ 7  9  6 10  9]
 [ 1  9  1  8  7]
 [ 6  5  7  3  2]
 [ 8  9  8  7  3]
 [ 3 10  3  6  7]]
Matriz 2:
[[ 2  8  5  9  1]
 [ 6  2  1  3  4]
 [ 9  1  3  1  5]
 [ 8  2  5  2  5]
 [ 5  2  9  2  9]
 [ 7  4 10  7  7]
 [ 5  1  9  8  9]
 [ 6  6  8  4  6]
 [ 9  8  9  8  6]
 [ 6  5  4  3  1]]
Suma Matricial:
[[ 3 10  9 18  6]
 [10 12  3  6 14]
 [15  6  8  2  7]
 [10  3  7  6  6]
 [11  7 14  9 14]
 [14 13 16 17 16]
 [ 6 10 10 16 16]
 [12 11 15  7  8]
 [17 17 17 15  9]
 [ 9 15  7  9  8]]
Resta Matricial:
[[-1 -6 -1  0  4]
 [-2  8  1  0  6]
 [-3  4  2  0 -3]
 [-6 -1 -3  2 -4]
 [ 1  3 -4  5 -4]
 [ 0  5 -4  3  2]
 [-4  8 -8  0 -2]
 [ 0 -1 -1 -1 -4]
 [-1  1 -1 -1 -3]
 [-3  5 -1  3  6]]
Multiplicación Matricial:
(array([[ 1,  2,  4,  9,  5],
       [ 4, 10,  2,  3, 10],
       [ 6,  5,  5,  1,  2],
       [ 2,  1,  2,  4,  1],
       [ 6,  5,  5,  7,  5],
       [ 7,  9,  6, 10,  9],
       [ 1,  9,  1,  8

---
### Ejercicio 15

Crea una matriz aleatoria de tamaño 4 , muestra por pantalla el valor minimo y maximo.

In [271]:
matriz = np.random.randint(1, 101, size=(4, 4))

print("Matriz Aleatoria:")
print(matriz)

valor_minimo = np.min(matriz)
valor_maximo = np.max(matriz)

print("Valor Mínimo:", valor_minimo)
print("Valor Máximo:", valor_maximo)


Matriz Aleatoria:
[[100  22  71  80]
 [ 41  54   9   6]
 [ 32  16  26  16]
 [ 72  58  72  69]]
Valor Mínimo: 6
Valor Máximo: 100
