# Ejercicios Numpy

---
### Ejercicio 1

Antes de empezar tenéis que importar la libreria adecuada para trabajar con Numpy.

In [13]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 23.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [14]:
import numpy as np

---
### Ejercicio 2


Crea un array de **una dimensión** con los 10 valores que tu quieras y muéstralo por pantalla:

In [15]:
array1D=np.array([1,2,3,4,5,6,7,8,9,10])
print(array1D)

[ 1  2  3  4  5  6  7  8  9 10]


---
### Ejercicio 3


Crea un array de distinto nombre al anterior de **dos dimensiones** con los 3x3 valores que tu quieras y muéstrala por pantalla:

In [16]:
array2D=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

print(array2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


---
### Ejercicio 4


Crea un array de distinto nombre a los anteriores de **tres dimensiones** con los 3x2x2 valores que tu quieras y muéstrala por pantalla:

In [17]:
array3D = np.array([[[1, 2],
                         [3, 4]],

                        [[5, 6],
                         [7, 8]],

                        [[9, 10],
                         [11, 12]]])

print(array3D)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


---
### Ejercicio 5

Muestra las **dimensiones, el tamaño y la forma** que tienen las tres matrices creadas anteriormente:

In [18]:
array1D=np.array([1,2,3,4,5,6,7,8,9,10])

array2D=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

array3D = np.array([[   [1, 2],
                         [3, 4]],

                        [[5, 6],
                         [7, 8]],

                        [[9, 10],
                         [11, 12]]])

print("Matriz 1D:")
print("Dimensiones:", array1D.ndim)
print("Tamaño:", array1D.size)
print("Forma:", array1D.shape)

print("\nMatriz 2D")
print("Dimensiones:", array2D.ndim)
print("Tamaño:", array2D.size)
print("Forma:", array2D.shape)

print("\nMatriz 3D:")
print("Dimensiones:", array3D.ndim)
print("Tamaño:", array3D.size)
print("Forma:", array3D.shape)

Matriz 1D:
Dimensiones: 1
Tamaño: 10
Forma: (10,)

Matriz 2D
Dimensiones: 2
Tamaño: 9
Forma: (3, 3)

Matriz 3D:
Dimensiones: 3
Tamaño: 12
Forma: (3, 2, 2)


---
### Ejercicio 6


Crea un array de una dimensión de tipo int8. En una de las posiciones pon el valor 1000. ¿Qué ocurre y porqué?

In [19]:
array1DInt8 = np.array([0, 0, 0], dtype=np.int8)

array1DInt8[1] = 1000

print(array1DInt8)

[  0 -24   0]


C:\Users\Jon\AppData\Local\Temp\ipykernel_10624\1048028275.py:3: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 1000 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  array1DInt8[1] = 1000


Da error porque en Python int8 ocupan 8bits (-127 a 127) y 1000 está fuera del rango. 

---
### Ejercicio 7


Crea un array de dos dimensiones de tipo float128 y luego muestra su tipo por pantalla:

In [20]:
# array2DFloat128 = np.array([[1.1, 2.2], [3.3, 4.4]], dtype=np.float128)

# print("Tipo del array2DFloat128:", array2DFloat128.dtype)

---
### Ejercicio 9

Crea un array con los 10 primeros multiplos de 2 en una sola instrucción y muestralo por pantalla

In [21]:
multiplosDe2 = np.arange(2, 21, 2)

print(multiplosDe2)

[ 2  4  6  8 10 12 14 16 18 20]


---
### Ejercicio 10

Crea la siguiente matriz 4x4 con nombre A44=
\begin{pmatrix}
2 & 5 & 0 & 10\\
7 & 3 & 8 & -9\\
3 & 0 & 1 & -1\\
12 & -1 & 0 & 41
\end{pmatrix}


In [22]:
A44 = np.array([
        [2, 5, 0, 10],
        [7, 3, 8, -9],
        [3, 0, 1, -1],
        [12, -1, 0, 41]
    ])

print(A44)

[[ 2  5  0 10]
 [ 7  3  8 -9]
 [ 3  0  1 -1]
 [12 -1  0 41]]


---
### Ejercicio 11

Usa la matriz A44 y muestra por pantalla una submatriz 2x2, por ejemplo
\begin{pmatrix}
3 & 8 \\
0 & 1 \\
\end{pmatrix}

In [23]:
A44 = np.array([
        [2, 5, 0, 10],
        [7, 3, 8, -9],
        [3, 0, 1, -1],
        [12, -1, 0, 41]
    ])

# Seleccionamos las filas 3,4 y las columnas 2,3 como nos pide
subMatriz = A44[2:4, 1:3]

print(subMatriz)


[[ 0  1]
 [-1  0]]


---
### Ejercicio 12

Genera un array 3x2 con valores aleatorios,muestrala y también imprime la matriz 2x3.

---
### Ejercicio 13

Compara los tiempos de ejecución entre una lista aleatoria de 1.000.000 de datos con una matriz aleatorio del mismo tamaño con Numpy.

---
### Ejercicio 14

Genera dos matrices con dimensiones 10x5 y muestra la suma, resta y multiplicación matricial.

In [24]:
matriz1 = np.random.randint(1, 11, size=(10, 5))  # Números aleatorios entre 1 y 10
matriz2 = np.random.randint(1, 11, size=(10, 5))  # Números aleatorios entre 1 y 10

print("Matriz 1:")
print(matriz1)
print("Matriz 2:")
print(matriz2)

suma = matriz1 + matriz2
print("Suma Matricial:")
print(suma)

resta = matriz1 - matriz2
print("Resta Matricial:")
print(resta)

multi = matriz1, matriz2
print("Multiplicación Matricial:")
print(multi)


Matriz 1:
[[ 2  3  9  6  1]
 [ 2  7  1  7  1]
 [10  9  1  5 10]
 [ 3  7  9  6  1]
 [ 4 10  5  7  6]
 [ 7  2  5  3  5]
 [ 1  2  8  3  3]
 [ 1  8  5 10 10]
 [ 8  1  5  4  9]
 [ 5 10  4  5  6]]
Matriz 2:
[[ 5  2  4  7  7]
 [ 9  6  1  5  9]
 [ 4 10  1  3  4]
 [ 2  6  9  3  6]
 [ 7  1  2  1 10]
 [ 8  5  6  2 10]
 [ 5  1  3  6  7]
 [ 1  6  6 10  9]
 [ 5  5  4  3  8]
 [ 8  8  4  4  5]]
Suma Matricial:
[[ 7  5 13 13  8]
 [11 13  2 12 10]
 [14 19  2  8 14]
 [ 5 13 18  9  7]
 [11 11  7  8 16]
 [15  7 11  5 15]
 [ 6  3 11  9 10]
 [ 2 14 11 20 19]
 [13  6  9  7 17]
 [13 18  8  9 11]]
Resta Matricial:
[[-3  1  5 -1 -6]
 [-7  1  0  2 -8]
 [ 6 -1  0  2  6]
 [ 1  1  0  3 -5]
 [-3  9  3  6 -4]
 [-1 -3 -1  1 -5]
 [-4  1  5 -3 -4]
 [ 0  2 -1  0  1]
 [ 3 -4  1  1  1]
 [-3  2  0  1  1]]
Multiplicación Matricial:
(array([[ 2,  3,  9,  6,  1],
       [ 2,  7,  1,  7,  1],
       [10,  9,  1,  5, 10],
       [ 3,  7,  9,  6,  1],
       [ 4, 10,  5,  7,  6],
       [ 7,  2,  5,  3,  5],
       [ 1,  2,  8,  3

---
### Ejercicio 15

Crea una matriz aleatoria de tamaño 4 , muestra por pantalla el valor minimo y maximo.

In [ ]:
matriz = np.random.randint(1, 101, size=(4, 4))

print("Matriz Aleatoria:")
print(matriz)

valor_minimo = np.min(matriz)
valor_maximo = np.max(matriz)

print("Valor Mínimo:", valor_minimo)
print("Valor Máximo:", valor_maximo)
